name: Go build and test

on:
  push:
    branches: [ master ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v -o ./ ./...

    - run: go tool buildid testbin
